service: retailpluse-backend

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1
  memorySize: 2048
  timeout: 30

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - '!node_modules/prisma/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/aws-sdk/**'
    # - 'node_modules/@codegenie/serverless-express'
    # - '!node_modules/@aws-sdk/**'

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
